### ISSUE TITLE
Unable to build `main` - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kkokosa** [ashmind/mirrorsharp#173]
On a fresh main clone, after successful `.\mirrorsharp.bat setup`, when doing `.\mirrorsharp.bat build` it throws:

```
> parcel build index.html --out-dir wwwroot --no-minify

‼  Parser "assets\JSAsset" failed to initialize when processing asset "app.js". Threw the following error:
Error: Cannot find module 'D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\@babel\compat-data\data\corejs3-shipped-proposals'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\v8-compile-cache\v8-compile-cache.js:194:30) falling back to RawAsset
‼  Parser "assets\JSAsset" failed to initialize when processing asset "app.js". Threw the following error:
Error: Cannot find module 'D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\@babel\compat-data\data\corejs3-shipped-proposals'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\v8-compile-cache\v8-compile-cache.js:194:30) falling back to RawAsset
‼  Parser "assets\JSAsset" failed to initialize when processing asset "app.js". Threw the following error:
Error: Cannot find module 'D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\@babel\compat-data\data\corejs3-shipped-proposals'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\v8-compile-cache\v8-compile-cache.js:194:30) falling back to RawAsset
×  Cannot read property 'length' of undefined
    at lineCounter (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\utils\lineCounter.js:3:30)
    at JSPackager.writeModule (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\packagers\JSPackager.js:127:60)
    at async JSPackager.addAsset (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\packagers\JSPackager.js:88:5)
    at async Bundle._addDeps (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\Bundle.js:250:5)
    at async Bundle._package (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\Bundle.js:202:5)
    at async Promise.all (index 2)
    at async Bundle.package (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\Bundle.js:202:5)
    at async Bundler.bundle (D:\github\tools\forks\mirrorsharp\Owin.Demo\node_modules\parcel\src\Bundler.js:325:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirrorsharp.owin.demo@0.0.0 build: `parcel build index.html --out-dir wwwroot --no-minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirrorsharp.owin.demo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Anything more I can add to diagnose this?

**Comment by ashmind** [comment]
Hmm, this seems like a new issue, related to node version nodejs/node#32852.
I'll pick a lazy path and just apply same packages as Asp.Net Core demo, which does not seem to have a problem.

**Comment by kkokosa** [comment]
Thanks, it works! Note: it is worth to delete `.cache` folder in Owin.Demo to have a fresh build.
