### ISSUE TITLE
Something failes to load when deploying MirrorSharp on a server

### ISSUE THREAD

**Issue by Sicos1977** [ashmind/mirrorsharp#180]
When I run my project in visual studio 2022 I have no problems but when deployed on IIS on a Windows 2019 server something failes to load. Does somebody know how I can hook into MirrorSharp to find out what is failing to load. I have no idea how I can retrieve the `LoaderExcptions`

```
Process information: 
    Process ID: 11772 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\XXXXXXXXXXX
 
Exception information: 
    Exception type: ReflectionTypeLoadException 
    Exception message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at MirrorSharp.Internal.Roslyn.RoslynLanguageBase.CreateHostServices(String featuresAssemblyName, String workspacesAssemblyName)
   at MirrorSharp.Internal.Roslyn.RoslynLanguageBase..ctor(String name, String featuresAssemblyName, String workspacesAssemblyName, IRoslynLanguageOptions options)
   at MirrorSharp.MirrorSharpOptions.<.ctor>b__3_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at MirrorSharp.Internal.LanguageManager.GetLanguage(String name)
   at MirrorSharp.Internal.MiddlewareBase.<WebSocketLoopAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

**Comment by Sicos1977** [comment]
Well it seemed to be assembly redirect in a app.config file from the service that is hosting mirrorsharp. 

Still it would be nice if there was a way to hook into the exception to retrieve some more information. This time I found it rather quick but the exception that is shown in the eventviewer is very difficult to read.

**Comment by ashmind** [comment]
Thanks for reporting! It's a fair point -- I could actually expose assembly name and `LoaderExceptions` directly for this one.
I'll look into this (no specific timeline promise).

**Comment by Sicos1977** [comment]
Any updates on this?

**Comment by ashmind** [comment]
Not yet, I haven't actively looked at the library for a while, but might take a look as part of the new upgrade work (no promises).
