### ISSUE TITLE
CM6: System.InvalidOperationException: Cannot select completion when completion list is not active.

### ISSUE THREAD

**Issue by ashmind** [ashmind/mirrorsharp#211]
```
session.js:121 Uncaught Error: System.InvalidOperationException: Cannot select completion when completion list is not active.
   at MirrorSharp.Internal.Handlers.Shared.CompletionSupport.SelectCompletionAsync(:7177/Int32 selectedIndex, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in c:\Development\mirrorsharp\Common\Internal\Handlers\Shared\CompletionSupport.cs:line 42
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(:7177/CancellationToken cancellationToken) in c:\Development\mirrorsharp\Common\Internal\Connection.cs:line 96
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(:7177/CancellationToken cancellationToken) in c:\Development\mirrorsharp\Common\Internal\Connection.cs:line 54
    at #receiveServerError (session.js:121:38)
    at #receiveMessage (session.js:136:33)
    at message (session.js:23:41)
    at WebSocket.message (connection.js:67:11)
```

**Comment by ashmind** [comment]
Might be fixed by latest completion improvements, let's monitor a bit

**Comment by sampletext32** [comment]
if sharplab utilizes the latest version, then this problem still exists.

Reproduction:
1. Clean input
2. Type "Gui"
3. Refresh page
4. Press "Ctrl + Space" / "Cmd + Space"
5. Press "Enter" (suggestion is not inserted)
6. Press "Enter" again. (Error is displayed on the right side)
![image](https://github.com/ashmind/mirrorsharp/assets/44116740/98c98a0d-14b2-4c58-8bdb-58bc9ea55af2)
