### ISSUE TITLE
Latest roslyn analyzers (version 4.10) give an exception

### ISSUE THREAD

**Issue by Sicos1977** [ashmind/mirrorsharp#224]
Exception information: 
    Exception type: ReflectionTypeLoadException 
    Exception message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at MirrorSharp.Internal.Roslyn.RoslynLanguageBase..ctor(String name, String featuresAssemblyName, String workspacesAssemblyName, IRoslynLanguageOptions options)
   at MirrorSharp.MirrorSharpOptions.<.ctor>b__3_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at MirrorSharp.Internal.LanguageManager.GetLanguage(String name)
   at MirrorSharp.Internal.MiddlewareBase.StartWorkSession()
   at MirrorSharp.Internal.MiddlewareBase.<WebSocketLoopAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Owin.Internal.Middleware.<<Invoke>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.OwinCallContext.<AcceptCallback>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSocketPipeline.<ProcessRequestImplAsync>d__9.MoveNext()

**Comment by Sicos1977** [comment]
Same issue with the 4.11 version... could you please make an updated nuget package?

**Comment by Sicos1977** [comment]
?????

**Comment by Sicos1977** [comment]
As long as there is no new nuget package and you want to use Roslyn 4.10 or 4.11 --> https://github.com/Sicos1977/mirrorsharp

You need to compile it yourself.

**Comment by ashmind** [comment]
Thanks for reporting (and the PR) -- fixed in [3.0.10](https://www.nuget.org/packages/MirrorSharp.Common/3.0.10) (just published)
